[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
urthr_net = "8CsDf7B1YU9HV136afSbYsY8eV2YeJUk5Sd2CpuLLiSb"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
