[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
urthr_net = "6xQqNSjG7Z3KMeMtWSPNRKpwVhzxLjcbBHSR4qa5SfTm"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
